volumes:
  ros-home:
    external: true

services:
  cair_unitree_tomographic:
    build: .
    image: cair_unitree_tomographic
    network_mode: host
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ros-home:/root
    environment:
      - UNITREE_ID
      - TERM
